-- ============================================================================
-- DSS-AC-065 R1  INSERT (7 temp rows)  [APPROVAL REQUIRED BEFORE EXECUTION]
-- Target: Oracle 19c development  DB user/schema CDC
--         192.168.174.65:1521/prod.enmotech.com  (project CLAUDE.md §11 dev DB)
-- Table : CDC / CDC_DATA_SOURCE_RUN_STATE  (ONLY this table is written)
-- Prefix: dss-fa065-r1-   (independent task prefix)
-- ============================================================================
-- S1 normal association -> SNAPSHOT_COMPLETED (enabled probe hosp-007 + enabled SOURCE 112-source-19c)
INSERT INTO CDC_DATA_SOURCE_RUN_STATE
 (CLIENT_ID, DATA_SOURCE_ID, SNAPSHOT_STATUS, SNAPSHOT_LAST_SEEN_AT, SNAPSHOT_COMPLETED_AT, UPDATED_AT)
VALUES ('hosp-007','112-source-19c','SNAPSHOT_COMPLETED',
        TO_DATE('2026-09-12 20:58:00','YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-09-12 20:58:30','YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-09-12 20:58:30','YYYY-MM-DD HH24:MI:SS'));
-- S2 normal association -> UNKNOWN status (enabled probe hosp-002 + enabled SOURCE 112-source-19c)
INSERT INTO CDC_DATA_SOURCE_RUN_STATE
 (CLIENT_ID, DATA_SOURCE_ID, SNAPSHOT_STATUS, SNAPSHOT_LAST_SEEN_AT, SNAPSHOT_COMPLETED_AT, UPDATED_AT)
VALUES ('hosp-002','112-source-19c','SNAPSHOT_FA065_UNKNOWN',
        TO_DATE('2026-09-12 20:57:00','YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-09-12 20:57:00','YYYY-MM-DD HH24:MI:SS'));
-- S3 orphan probe end (CLIENT_ID has no CDC_CLIENT_MULTIPLE config) + enabled SOURCE
INSERT INTO CDC_DATA_SOURCE_RUN_STATE
 (CLIENT_ID, DATA_SOURCE_ID, SNAPSHOT_STATUS, SNAPSHOT_LAST_SEEN_AT, SNAPSHOT_COMPLETED_AT, UPDATED_AT)
VALUES ('dss-fa065-r1-client-orphan','112-source-19c','SNAPSHOT_RUNNING',
        TO_DATE('2026-09-12 20:56:00','YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-09-12 20:56:00','YYYY-MM-DD HH24:MI:SS'));
-- S4 orphan source (DATA_SOURCE_ID has no CDC_DATA_SOURCE config) + enabled probe hosp-0061
INSERT INTO CDC_DATA_SOURCE_RUN_STATE
 (CLIENT_ID, DATA_SOURCE_ID, SNAPSHOT_STATUS, SNAPSHOT_LAST_SEEN_AT, SNAPSHOT_COMPLETED_AT, UPDATED_AT)
VALUES ('hosp-0061','dss-fa065-r1-source-orphan','SNAPSHOT_COMPLETED',
        TO_DATE('2026-09-12 20:55:00','YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-09-12 20:55:30','YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2026-09-12 20:55:30','YYYY-MM-DD HH24:MI:SS'));
-- S5 reference EXISTING disabled probe config (CCFG-AC-R1-OFF, FG_ACTIVE='0', CLIENT_DESC NULL)
INSERT INTO CDC_DATA_SOURCE_RUN_STATE
 (CLIENT_ID, DATA_SOURCE_ID, SNAPSHOT_STATUS, SNAPSHOT_LAST_SEEN_AT, SNAPSHOT_COMPLETED_AT, UPDATED_AT)
VALUES ('CCFG-AC-R1-OFF','112-source-19c','SNAPSHOT_RUNNING',
        TO_DATE('2026-09-12 20:54:00','YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-09-12 20:54:00','YYYY-MM-DD HH24:MI:SS'));
-- S6 reference EXISTING disabled SOURCE config (199-source, FG_ACTIVE='0') + enabled probe CCFG-AC-R1-ON
INSERT INTO CDC_DATA_SOURCE_RUN_STATE
 (CLIENT_ID, DATA_SOURCE_ID, SNAPSHOT_STATUS, SNAPSHOT_LAST_SEEN_AT, SNAPSHOT_COMPLETED_AT, UPDATED_AT)
VALUES ('CCFG-AC-R1-ON','199-source','SNAPSHOT_RUNNING',
        TO_DATE('2026-09-12 20:53:00','YYYY-MM-DD HH24:MI:SS'),
        NULL,
        TO_DATE('2026-09-12 20:53:00','YYYY-MM-DD HH24:MI:SS'));
-- S7 reference EXISTING non-SOURCE category data source (company-target-doris-v4, category='target', FG_ACTIVE='1') + enabled probe hosp-012
INSERT INTO CDC_DATA_SOURCE_RUN_STATE
 (CLIENT_ID, DATA_SOURCE_ID, SNAPSHOT_STATUS, SNAPSHOT_LAST_SEEN_AT, SNAPSHOT_COMPLETED_AT, UPDATED_AT)
VALUES ('hosp-012','company-target-doris-v4','SNAPSHOT_RUNNING',
        NULL,
        NULL,
        TO_DATE('2026-09-12 20:52:00','YYYY-MM-DD HH24:MI:SS'));
COMMIT;
