-- DATA-SOURCE-SNAPSHOT-STATUS-IMPLEMENTATION-001-R1 / R1-02 提交后只读复核（新会话，无写操作）
set pagesize 400 linesize 300 verify off feedback on echo on
col client_id format a22
col data_source_id format a22
col snapshot_status format a20
col last_seen format a20
col completed format a20
col updated format a20
spool /agent/cdc-config-platform/docs/features/data-source-snapshot-status/evidence/DATA-SOURCE-SNAPSHOT-STATUS-IMPLEMENTATION-001-R1/db/003-verify-reads.spool.log

SELECT 'dssr1-0906- RUN_STATE 行数' AS check_item, COUNT(*) AS cnt
FROM CDC_DATA_SOURCE_RUN_STATE
WHERE CLIENT_ID LIKE 'c-dssr1-0906-%' OR DATA_SOURCE_ID LIKE 's-dssr1-0906-%';

SELECT 'dssr1-0906- CLIENT_MULTIPLE 行数' AS check_item, COUNT(*) AS cnt
FROM CDC_CLIENT_MULTIPLE WHERE CLIENT_ID LIKE 'c-dssr1-0906-%';

SELECT 'dssr1-0906- DATA_SOURCE 行数' AS check_item, COUNT(*) AS cnt
FROM CDC_DATA_SOURCE WHERE DATA_SOURCE_ID LIKE 's-dssr1-0906-%';

SELECT 'RUNNING(12)' AS grp, COUNT(*) cnt FROM CDC_DATA_SOURCE_RUN_STATE WHERE SNAPSHOT_STATUS='SNAPSHOT_RUNNING' AND CLIENT_ID LIKE 'c-dssr1-0906-%'
UNION ALL SELECT 'COMPLETED(11)', COUNT(*) FROM CDC_DATA_SOURCE_RUN_STATE WHERE SNAPSHOT_STATUS='SNAPSHOT_COMPLETED' AND CLIENT_ID LIKE 'c-dssr1-0906-%'
UNION ALL SELECT 'UNKNOWN(6)', COUNT(*) FROM CDC_DATA_SOURCE_RUN_STATE WHERE SNAPSHOT_STATUS IN ('SNAPSHOT_STALE','UNKNOWN','STARTING','SNAPSHOT_UNKNOWN','UNKNOWN_MODE') AND CLIENT_ID LIKE 'c-dssr1-0906-%';

SELECT TO_CHAR(SNAPSHOT_LAST_SEEN_AT,'YYYY-MM-DD HH24:MI:SS') last_seen,
       TO_CHAR(SNAPSHOT_COMPLETED_AT,'YYYY-MM-DD HH24:MI:SS') completed,
       TO_CHAR(UPDATED_AT,'YYYY-MM-DD HH24:MI:SS') updated,
       CLIENT_ID, DATA_SOURCE_ID, SNAPSHOT_STATUS
FROM CDC_DATA_SOURCE_RUN_STATE
WHERE CLIENT_ID LIKE 'c-dssr1-0906-%'
ORDER BY UPDATED_AT DESC, CLIENT_ID, DATA_SOURCE_ID;

SELECT CLIENT_ID, SUBSTR(CLIENT_DESC,1,40) desc_prefix, FG_ACTIVE
FROM CDC_CLIENT_MULTIPLE WHERE CLIENT_ID LIKE 'c-dssr1-0906-%' ORDER BY CLIENT_ID;

SELECT DATA_SOURCE_ID, DATA_SOURCE_ORG, DATA_SOURCE_CATEGORY, FG_ACTIVE
FROM CDC_DATA_SOURCE WHERE DATA_SOURCE_ID LIKE 's-dssr1-0906-%' ORDER BY DATA_SOURCE_ID;
exit
